#!/bin/bash
set -e

# Temporary ~hack. Will be moved to GHA, and won't assume that `vctrs` is
# available "next door" in the local folder.

# ==============================================================================
# CONFIGURATION
# ==============================================================================

VCTRS_SRC="../vctrs/src"       # Upstream source
TARGET_DIR="src/vctrs"         # Local vendor dir
COMPILATION_UNIT="src/vctrs.c" # Unity build file

SEEDS=(
  "vctrs.h"
  "type-date-time.c"
  "growable.c"
  "slice-array.c"
  "slice-assign-array.c"
)

# ==============================================================================
# 1. CLEAN & PREP
# ==============================================================================

if [[ ! -d "$VCTRS_SRC" ]]; then
  echo "Error: Cannot find vctrs source at $VCTRS_SRC"
  exit 1
fi

echo "Wiping $TARGET_DIR..."
rm -rf "$TARGET_DIR"
mkdir -p "$TARGET_DIR"

# ==============================================================================
# 2. RECURSIVE DEPENDENCY CRAWLER
# ==============================================================================

declare -A SEEN
QUEUE=("${SEEDS[@]}")

echo "Scanning dependencies starting from: ${SEEDS[*]}"

while [ ${#QUEUE[@]} -gt 0 ]; do
  # Pop first item
  FILE="${QUEUE[0]}"
  QUEUE=("${QUEUE[@]:1}")

  # Skip if already processed
  if [[ -n "${SEEN[$FILE]}" ]]; then continue; fi
  SEEN[$FILE]=1

  SRC_FILE="$VCTRS_SRC/$FILE"
  DEST_FILE="$TARGET_DIR/$FILE"

  # Skip if file doesn't exist in upstream
  if [[ ! -f "$SRC_FILE" ]]; then continue; fi

  # A. COPY FILE (Handle subdirectories!)
  # Ensure the directory exists (e.g., src/vctrs/decl/)
  mkdir -p "$(dirname "$DEST_FILE")"
  cp "$SRC_FILE" "$DEST_FILE"

  # B. AUTO-PAIR .h WITH .c
  if [[ "$FILE" == *.h ]]; then
    C_PAIR="${FILE%.h}.c"
    if [[ -f "$VCTRS_SRC/$C_PAIR" && "$C_PAIR" != "init.c" ]]; then
      QUEUE+=("$C_PAIR")
    fi
  fi

  # C. FIND CHILDREN
  # grep #include "...", extract filename
  INCLUDES=$(grep '^#include "' "$SRC_FILE" | sed -E 's/^#include "(.*)"/\1/')

  for INC in $INCLUDES; do
    # Only verify existence here to keep queue clean
    if [[ -f "$VCTRS_SRC/$INC" ]]; then
      QUEUE+=("$INC")
    fi
  done
done

echo "Vendored ${#SEEN[@]} files."

# ==============================================================================
# 3. GENERATE src/vctrs.c
# ==============================================================================

echo "Generating $COMPILATION_UNIT..."

{
  echo "/* Auto-generated by update-vctrs.sh */"
  echo "/* Do not edit manually. */"
  echo ""

  # Find all .c files we just copied
  # Note: -name "*.c" might find files in subdirs, we need relative paths
  # We cd into TARGET_DIR to get clean relative paths
  ALL_C=$(cd "$TARGET_DIR" && find . -name "*.c" | sed 's|^\./||')

  # Priority Includes
  for PRIORITY in "globals.c" "utils.c" "utils-dispatch.c"; do
    if echo "$ALL_C" | grep -q "$PRIORITY"; then
      echo "#include \"vctrs/$PRIORITY\""
    fi
  done

  # The rest (alphabetical)
  echo "$ALL_C" | sort | while read -r F; do
    if [[ "$F" != "globals.c" && "$F" != "utils.c" && "$F" != "utils-dispatch.c" ]]; then
      echo "#include \"vctrs/$F\""
    fi
  done

} > "$COMPILATION_UNIT"

echo "Done."
